openapi: 3.0.3
info:
  title: Hotel CRUD API
  version: 1.0.0
  description: API REST para gestionar hoteles.

servers:
  - url: https://localhost:8080/api/v1

paths:
  /hotels:
    get:
      operationId: getHotels
      summary: Get all hotels
      tags: [Hotels]
      responses:
        '200':
          description: Get all hotels
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Hotel'
        '500':
          $ref: "#/components/responses/500Response"
        '429':
          $ref: "#/components/responses/429Response"

    post:
      operationId: createHotel
      summary: Create new hotel
      tags: [Hotels]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/HotelInput'
      responses:
        '201':
          description: Hotel created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Hotel'
        '500':
          $ref: "#/components/responses/500Response"
        '429':
          $ref: "#/components/responses/429Response"

  /hotels/{id}:
    get:
      operationId: getHotel
      summary: Get hotel by UUID
      tags: [Hotels]
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Hotel details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Hotel'
        '500':
          $ref: "#/components/responses/500Response"
        '429':
          $ref: "#/components/responses/429Response"

    put:
      operationId: updateHotel
      summary: Update a hotel by ID
      tags: [Hotels]
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
            format: uuid
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/HotelInput'
      responses:
        '200':
          description: Hotel updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Hotel'
        '404':
          $ref: "#/components/responses/404Response"
        '500':
          $ref: "#/components/responses/500Response"
        '429':
          $ref: "#/components/responses/429Response"

    delete:
      operationId: deleteHotel
      summary: Delete a hotel by ID
      tags: [Hotels]
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '204':
          description: Hotel deleted successfully
        '404':
          $ref: "#/components/responses/404Response"
        '500':
          $ref: "#/components/responses/500Response"
        '429':
          $ref: "#/components/responses/429Response"
security:
  - bearerAuth: []
components:
  headers:
    XRateLimitRemaining:
      description: 'This header informs number request before of reject'
      example: 100
      schema:
        type: integer
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  responses:
    404Response:
      description: Hotel not found
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/Error"
          examples:
            404:
              value:
                error: HOTELS-ERROR-00404
                message: Hotel not found
    500Response:
      description: Error unexpected
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/Error"
          examples:
            500:
              value:
                error: HOTELS-ERROR-00500
                message: Error unexpected
    429Response:
      description: Too many requests
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/Error"
          examples:
            429:
              value:
                error: HOTELS-ERROR-00429
                message: Too many Requests. You have exhausted your API Request Quota
  schemas:
    Error:
      type: object
      properties:
        error:
          type: string
        message:
          type: string
      required:
        - error
        - message
    Hotel:
      allOf:
        - type: object
          properties:
            id:
              type: string
              format: uuid
              readOnly: true
          required:
            - id
        - $ref: '#/components/schemas/HotelInput'
    HotelInput:
      type: object
      properties:
        name:
          x-field-extra-annotation: '@com.myenterprise.rest.annotation.SanitizeHTML'
          type: string
          example: Hotel Continental
        description:
          x-field-extra-annotation: '@com.myenterprise.rest.annotation.SanitizeHTML'
          type: string
          example: This is hotel is the best hotel of the world
        address:
          x-field-extra-annotation: '@com.myenterprise.rest.annotation.SanitizeHTML'
          type: string
          example: Street Falsa 123
        city:
          x-field-extra-annotation: '@com.myenterprise.rest.annotation.SanitizeHTML'
          type: string
          example: Madrid
        rating:
          type: number
          format: float
          example: 4.5
        has_wifi:
          type: boolean
          example: true
      required: [ name, address, city, rating, has_wifi ]