spring:
  datasource:
    url: jdbc:h2:file:./database
    username: sa
    password: sa
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    open-in-view: false
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: true
  cache:
    cache-names:
      - rate-limit-buckets

management:
  endpoints:
    web:
      cors:
        allowed-origins: "http://localhost:8080"
        allowed-methods: "*"
        path-pattern: "/**"

bucket4j:
  enabled: true
  filters:
    - cache-name: rate-limit-buckets
      url: /api/.*
      strategy: first
      http-response-body: "{ \"error\": \"HOTELS-ERROR-00429\", \"message\": \"Too many Requests. You have exhausted your API Request Quota\" }"
      rate-limits:
        - cache-key: "getRemoteAddr()"
          bandwidths:
            - capacity: 5
              time: 1
              unit: minutes