/*
 *   MIT License
 *
 *  Copyright (c) 2026 cleanet
 *
 *  Permission is hereby granted, free of charge, to any person obtaining a copy
 *  of this software and associated documentation files (the "Software"), to deal
 *  in the Software without restriction, including without limitation the rights
 *  to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 *  copies of the Software, and to permit persons to whom the Software is
 *  furnished to do so, subject to the following conditions:
 *
 *  The above copyright notice and this permission notice shall be included in all
 *  copies or substantial portions of the Software.
 *
 *  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 *  IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 *  FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 *  AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 *  LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 *  OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 *  SOFTWARE.
 *
 * Code generated by Proton Lumo
 */
package com.myenterprise.rest.annotation.validatersql;

import com.myenterprise.rest.utils.ResponseUtils;
import cz.jirutka.rsql.parser.RSQLParser;
import cz.jirutka.rsql.parser.ast.ComparisonNode;
import cz.jirutka.rsql.parser.ast.LogicalNode;
import cz.jirutka.rsql.parser.ast.LogicalOperator;
import cz.jirutka.rsql.parser.ast.Node;
import jakarta.servlet.http.HttpServletRequest;
import jakarta.servlet.http.HttpServletResponse;
import org.jetbrains.annotations.NotNull;
import org.springframework.core.DefaultParameterNameDiscoverer;
import org.springframework.core.MethodParameter;
import org.springframework.stereotype.Component;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.method.HandlerMethod;
import org.springframework.web.servlet.HandlerInterceptor;

import java.util.*;

/**
 * {@code ValidateRsqlHandlerInterceptor} intercepts incoming HTTP requests and validates
 * any method arguments annotated with {@link ValidateRsql}. It parses the supplied RSQL
 * expression, checks depth, operator count, allowed operators, logical comparators and,
 * optionally, permitted fields. Errors are written back to the client via
 * {@link ResponseUtils}.
 *
 * <p>This interceptor is registered as a Spring {@code @Component} and therefore
 * participates automatically in the MVC handler chain.</p>
 *
 * <p>Only read‑only operations are performed – the interceptor never mutates the
 * request or the controller arguments.</p>
 */
@Component
public class ValidateRsqlHandlerInterceptor implements HandlerInterceptor {

    /**
     * Helper used when the project is not compiled with {@code -parameters}.
     * It discovers method parameter names via reflection.
     */
    private final DefaultParameterNameDiscoverer nameDiscoverer = new DefaultParameterNameDiscoverer();

    /**
     * Called before the actual controller method is invoked.
     *
     * @param request  the current HTTP request
     * @param response the current HTTP response
     * @param handler  the chosen handler to execute, typically a {@link HandlerMethod}
     * @return {@code true} to continue processing, {@code false} to abort (error already written)
     * @throws Exception if an unexpected error occurs while processing the request
     */
    @Override
    public boolean preHandle(@NotNull HttpServletRequest request,
                             @NotNull HttpServletResponse response,
                             @NotNull Object handler) throws Exception {

        boolean isNotRequestRestAPI = ! (handler instanceof HandlerMethod);
        if (isNotRequestRestAPI) {
            return true;
        }
        HandlerMethod handlerMethod = (HandlerMethod) handler;

        List<MethodParameter> parameters = Arrays.stream(handlerMethod.getMethodParameters()).filter(parameter ->
                parameter.hasParameterAnnotation(ValidateRsql.class)
        ).toList();

        for (MethodParameter methodParameter : parameters ) {

            ValidateRsql annotation = methodParameter.getParameterAnnotation(ValidateRsql.class);

            String paramName = getQueryParameterName(methodParameter);
            if (paramName == null) {
                ResponseUtils.writeErrorResponse(
                        response,
                        "Invalid configuration: unable to resolve query‑param name for @ValidateRsql parameter.",
                        HttpServletResponse.SC_INTERNAL_SERVER_ERROR,
                        "HOTELS-ERROR-50001");
                return false;
            }

            String parameterValue = request.getParameter(paramName);

            boolean isOptionalParameter = parameterValue == null;
            if (isOptionalParameter) {
                continue;
            }
            try {
                validateRsql(parameterValue, annotation);
            } catch (IllegalArgumentException error) {
                ResponseUtils.writeErrorResponse(
                        response,
                        error.getMessage(),
                        HttpServletResponse.SC_BAD_REQUEST,
                        "HOTELS-ERROR-40002");
                return false;
            } catch (Exception error) {
                ResponseUtils.writeErrorResponse(
                        response,
                        "Unable to parse RSQL expression.",
                        HttpServletResponse.SC_BAD_REQUEST,
                        "HOTELS-ERROR-40003");
                error.printStackTrace();
                return false;
            }
        }
        return true;
    }

    /**
     * Determines the name of the HTTP query‑parameter that corresponds to the given
     * {@link MethodParameter}.
     *
     * <p>The method first looks for a {@link RequestParam} annotation. If the annotation
     * supplies a non‑blank {@code name} or {@code value}, that value is returned.
     * Otherwise, the parameter name is obtained via {@link DefaultParameterNameDiscoverer},
     * which works when the code is compiled with {@code -parameters} or when the
     * discoverer can infer the name.</p>
     *
     * @param methodParameter the method parameter to inspect
     * @return the query‑parameter name, or {@code null} if it cannot be resolved
     */
    private String getQueryParameterName(@NotNull MethodParameter methodParameter) {
        // If contains @RequestParam(name = "...") or @RequestParam(value = "...") the queryPa
        RequestParam parameter = methodParameter.getParameterAnnotation(RequestParam.class);
        boolean hasRequestParamAnnotation = parameter != null;

        if ( hasRequestParamAnnotation && !parameter.name().isBlank()) {
            return parameter.name();
        }
        if (hasRequestParamAnnotation && !parameter.value().isBlank()) {
            return parameter.value();
        }

        // Use Introspection for get the parameter name based to variable name
        return Objects.requireNonNull(
                nameDiscoverer.getParameterNames(
                        Objects.requireNonNull(methodParameter.getMethod())
                )
        )[methodParameter.getParameterIndex()];
    }

    /**
     * Core RSQL validation routine.
     *
     * <p>The method parses the supplied RSQL string, then checks the following
     * constraints defined in the {@link ValidateRsql} annotation:</p>
     * <ul>
     *   <li>Maximum tree depth</li>
     *   <li>Maximum number of comparison operators</li>
     *   <li>Allowed comparison operators (e.g. {@code ==}, {@code !=})</li>
     *   <li>Allowed logical operators (AND / OR)</li>
     *   <li>Optional field whitelist</li>
     * </ul>
     *
     * @param rsql the raw RSQL expression supplied by the client
     * @param annotation  the annotation instance containing validation rules
     * @throws IllegalArgumentException if any of the validation rules are violated
     */
    private void validateRsql(String rsql, ValidateRsql annotation) {
        RSQLParser parser = new RSQLParser();
        Node rootNode = parser.parse(rsql);

        int depth = computeDepth(rootNode);
        if (depth > annotation.depth()) {
            throw new IllegalArgumentException(
                    "Maximum allowed depth is %d but expression depth is %d".formatted(annotation.depth(), depth));
        }

        int operatorCount = countOperators(rootNode);
        if (operatorCount > annotation.maxOperators()) {
            throw new IllegalArgumentException(
                    "Maximum allowed operators is %d but expression contains %d".formatted(annotation.maxOperators(), operatorCount));
        }

        validateAllowedOperators(rootNode, annotation.allowOperators());

        validateAllowedLogicalOperators(rootNode, annotation.allowComparators());

        if (annotation.validateFields()) {
            validateFields(rootNode, annotation.fields());
        }
    }

    /**
     * Recursively computes the maximum depth of the AST rooted at {@code node}.
     *
     * @param node the current AST node
     * @return the depth of the subtree (leaf nodes have depth 1)
     */
    private int computeDepth(Node node) {
        if (node instanceof LogicalNode logicalNode) {
            int max = 0;
            for (var child : logicalNode.getChildren()) {
                max = Math.max(max, computeDepth(child));
            }
            return max + 1;
        }
        return 1;
    }

    /**
     * Counts how many {@link ComparisonNode}s appear in the AST.
     *
     * @param node the current AST node
     * @return the total number of comparison operators in the subtree
     */
    private int countOperators(Node node) {
        if (node instanceof ComparisonNode) {
            return 1;
        }
        if (node instanceof LogicalNode logicalNode) {
            int sum = 0;
            for (var child : logicalNode.getChildren()) {
                sum += countOperators(child);
            }
            return sum;
        }
        return 0;
    }

    /**
     * Checks that every comparison operator used in the AST is present in the
     * {@code allowed} array.
     *
     * @param node    the current AST node
     * @param allowed the set of permitted {@link Operators}
     * @throws IllegalArgumentException if a disallowed operator is encountered
     */
    private void validateAllowedOperators(Node node,
                                          Operators[] allowed) {
        var allowedSet = EnumSet.noneOf(Operators.class);
        Collections.addAll(allowedSet, allowed);

        if (node instanceof ComparisonNode comparisonNode) {
            String operatorSymbol = comparisonNode.getOperator().getSymbol();
            Operators operatorEnum = mapSymbolToOperator(operatorSymbol);
            if (!allowedSet.contains(operatorEnum)) {
                throw new IllegalArgumentException("Operator not allowed: " + operatorSymbol);
            }
        } else if (node instanceof LogicalNode logicalNode) {
            for (var child : logicalNode.getChildren()) {
                validateAllowedOperators(child, allowed);
            }
        }
    }

    /**
     * Translates an RSQL operator symbol (e.g. {@code "=="} ) into the
     * corresponding {@link Operators} enum constant.
     *
     * @param symbol the textual representation of the operator
     * @return the matching {@link Operators} value
     * @throws IllegalArgumentException if the symbol does not correspond to any known operator
     */
    private Operators mapSymbolToOperator(String symbol) {
        return switch (symbol) {
            case "==" -> Operators.EQUAL;
            case "!=" -> Operators.NOT_EQUAL;
            case ">", "=gt=" -> Operators.GREATER_THAN;
            case ">=", "=ge=" -> Operators.GREATER_THAN_OR_EQUAL;
            case "<", "=lt="  -> Operators.LESS_THAN;
            case "<=", "=le=" -> Operators.LESS_THAN_OR_EQUAL;
            case "=in=" -> Operators.IN;
            case "=out=" -> Operators.NOT_IN;
            default -> throw new IllegalArgumentException("Operator unknown: " + symbol);
        };
    }

    /**
     * Ensures that every logical operator (AND / OR) used in the AST is among the
     * {@code allowed} set.
     *
     * @param node    the current AST node
     * @param allowed the permitted {@link LogicalOperator}s
     * @throws IllegalArgumentException if a disallowed logical operator is found
     */
    private void validateAllowedLogicalOperators(Node node,
                                                 LogicalOperator[] allowed) {
        var allowedSet = EnumSet.noneOf(LogicalOperator.class);
        Collections.addAll(allowedSet, allowed);

        if (node instanceof LogicalNode logicalNode) {
            if (!allowedSet.contains(logicalNode.getOperator())) {
                throw new IllegalArgumentException("logic operator not allowed: " + logicalNode.getOperator());
            }
            for (var child : logicalNode.getChildren()) {
                validateAllowedLogicalOperators(child, allowed);
            }
        }
    }

    /**
     * Validates that all field selectors referenced in the RSQL expression are
     * part of the whitelist supplied via {@code allowedFields}.
     *
     * @param node          the current AST node
     * @param allowedFields an array of permitted field names
     * @throws IllegalArgumentException if a field outside the whitelist is used
     */
    private void validateFields(Node node, String[] allowedFields) {
        var allowedSet = Set.of(allowedFields);
        if (node instanceof ComparisonNode comparisonNode) {
            String selector = comparisonNode.getSelector();
            if (!allowedSet.contains(selector)) {
                throw new IllegalArgumentException("Field not allowed: " + selector);
            }
        } else if (node instanceof LogicalNode ln) {
            for (var child : ln.getChildren()) {
                validateFields(child, allowedFields);
            }
        }
    }
}