/*
 *   MIT License
 *
 *  Copyright (c) 2026 cleanet
 *
 *  Permission is hereby granted, free of charge, to any person obtaining a copy
 *  of this software and associated documentation files (the "Software"), to deal
 *  in the Software without restriction, including without limitation the rights
 *  to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 *  copies of the Software, and to permit persons to whom the Software is
 *  furnished to do so, subject to the following conditions:
 *
 *  The above copyright notice and this permission notice shall be included in all
 *  copies or substantial portions of the Software.
 *
 *  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 *  IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 *  FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 *  AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 *  LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 *  OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 *  SOFTWARE.
 *
 * Generated by Proton Lumo
 */
package com.myenterprise.rest.annotation.sanitizehtml;

import com.myenterprise.rest.dto.JsonDto;
import com.fasterxml.jackson.databind.ObjectMapper;

import java.io.IOException;
import java.io.InputStream;
import java.util.ArrayList;
import java.util.List;

/**
 * Utility class that generates JSON payloads from a static template file
 * (<code>response.json</code>) located on the class‑path.
 *
 * <p>The class is deliberately final and has a private constructor to prevent
 * instantiation – it only provides static helper methods.</p>
 *
 * <p>Two flavours are offered:</p>
 * <ul>
 *   <li>{@link #generateJsonArray(int)} – creates a JSON array containing a
 *       configurable number of identical {@link JsonDto} objects.</li>
 *   <li>{@link #generateSingleJson()} – creates a single JSON object based on
 *       the same template.</li>
 * </ul>
 *
 * <p>Both methods read the template once per invocation, deserialize it into a
 * {@link JsonDto} using Jackson’s {@link ObjectMapper}, and then serialise the
 * result(s) back to a pretty‑printed JSON string.</p>
 */
public final class JsonGenerator {

    /** Private constructor to prevent instantiation. */
    private JsonGenerator() {}

    /**
     * Generates a JSON array containing {@code elementCount} copies of the
     * {@link JsonDto} represented by the <code>response.json</code> template.
     *
     * @param elementCount the number of elements to place in the resulting array;
     *                     must be non‑negative
     * @return a pretty‑printed JSON array as a {@link String}
     * @throws IOException if the template file cannot be read or deserialised
     */
    public static String generateJsonArray(int elementCount) throws IOException {

        InputStream stream = JsonGenerator.class.getClassLoader()
                .getResourceAsStream("response.json");

        assert stream != null;
        String originalJson = new String(stream.readAllBytes());

        List<JsonDto> list = new ArrayList<>(elementCount);
        for (int index = 0; index < elementCount; index++) {

            JsonDto dto = new ObjectMapper().readValue(
                    originalJson,
                    JsonDto.class
            );
            list.add(dto);
        }

        return new ObjectMapper()
                .writerWithDefaultPrettyPrinter()
                .writeValueAsString(list);
    }

    /**
     * Generates a single JSON object based on the <code>response.json</code>
     * template.
     *
     * @return a pretty‑printed JSON representation of the {@link JsonDto}
     * @throws IOException if the template file cannot be read or deserialised
     */
    public static String generateSingleJson() throws IOException {


        InputStream stream = JsonGenerator.class.getClassLoader()
                .getResourceAsStream("response.json");
        assert stream != null;
        String originalJson = new String(stream.readAllBytes());

        JsonDto dto = new ObjectMapper().readValue(
                originalJson,
                JsonDto.class
        );

        return new ObjectMapper()
                .writerWithDefaultPrettyPrinter()
                .writeValueAsString(dto);
    }
}