/*
 *   MIT License
 *
 *  Copyright (c) 2026 cleanet
 *
 *  Permission is hereby granted, free of charge, to any person obtaining a copy
 *  of this software and associated documentation files (the "Software"), to deal
 *  in the Software without restriction, including without limitation the rights
 *  to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 *  copies of the Software, and to permit persons to whom the Software is
 *  furnished to do so, subject to the following conditions:
 *
 *  The above copyright notice and this permission notice shall be included in all
 *  copies or substantial portions of the Software.
 *
 *  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 *  IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 *  FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 *  AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 *  LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 *  OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 *  SOFTWARE.
 *
 * Generated by Proton Lumo
*/
package com.myenterprise.rest.annotation.sanitizehtml;

import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.databind.ObjectWriter;
import com.myenterprise.rest.dto.JsonSanitizeDto;
import org.junit.jupiter.api.Test;

import java.io.InputStream;
import java.util.List;

import static org.hibernate.validator.internal.util.Contracts.assertNotNull;
import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertNotEquals;

/**
 * Unit tests for verifying that HTML sanitization works correctly when
 * deserialising {@link JsonSanitizeDto} objects from JSON payloads.
 *
 * <p>The tests load sample JSON files from the test resources folder,
 * deserialize them into DTO instances, re‑serialise those instances and
 * finally confirm that any potentially dangerous HTML (e.g. a script tag)
 * has been stripped out.</p>
 *
 * <p>These tests deliberately compare the “pretty‑printed” original JSON
 * with the pretty‑printed serialised version – they are expected to differ
 * because the sanitization process modifies the {@code description}
 * field.</p>
 *
 * <p>No modification of business logic occurs; the class solely validates
 * the behaviour of {@link JsonSanitizeDto#toJsonString()} and the Jackson
 * mapping configuration.</p>
 */
public class SanitizeHtmlTest {

    /** Shared {@link ObjectMapper} instance used for JSON (de)serialisation. */
    private final ObjectMapper mapper = new ObjectMapper();

    /**
     * Writer that produces indented (pretty‑printed) JSON output.
     * This makes the comparison of JSON strings easier to read during debugging.
     */
    private final ObjectWriter prettyWriter = mapper.writerWithDefaultPrettyPrinter();

    /**
     * Tests deserialization of a JSON array containing several {@link JsonSanitizeDto}
     * objects and verifies that sanitization removes unsafe HTML from each element.
     *
     * @throws Exception if reading the resource or (de)serialising fails.
     */
    @Test
    public void deserializeList() throws Exception {
        InputStream stream = getClass().getClassLoader().getResourceAsStream("responseList.json");
        assert stream != null;
        assertNotNull(stream, "Not found responseList.json");

        String originalJson = new String(stream.readAllBytes());

        String originalPretty = prettyWriter.writeValueAsString(
                mapper.readTree(originalJson)
        );

        List<JsonSanitizeDto> example = mapper.readValue(
                originalJson,
                new TypeReference<>() {}
        );

        String serializedPretty = prettyWriter.writeValueAsString(example);

        List<JsonSanitizeDto> serializedPrettyObject = mapper.readValue(
                serializedPretty,
                new TypeReference<>() {}
        );

        assertNotEquals(
                originalPretty,
                serializedPretty
        );
        assertFalse(serializedPrettyObject.isEmpty());
        assertFalse(serializedPrettyObject.get(0).getDescription()
                .contains("<script>alert('xss')</script>"));
    }

    /**
     * Tests deserialization of a single {@link JsonSanitizeDto} object and checks that
     * the sanitization logic removes any embedded script tags from its description.
     *
     * @throws Exception if reading the resource or (de)serialising fails.
     */
    @Test
    public void deserialize() throws Exception {
        InputStream stream = getClass().getClassLoader().getResourceAsStream("response.json");
        assert stream != null;
        assertNotNull(stream, "Not found response.json");
        String originalJson = new String(stream.readAllBytes());

        String originalPretty = prettyWriter.writeValueAsString(
                mapper.readTree(originalJson)
        );

        JsonSanitizeDto example = mapper.readValue(
                originalJson,
                JsonSanitizeDto.class
        );
        JsonSanitizeDto serializedPrettyObject = mapper.readValue(
                example.toJsonString(),
                JsonSanitizeDto.class
        );

        assertNotEquals(
                originalPretty,
                example.toJsonString()
        );

        assertFalse(serializedPrettyObject.getDescription()
                .contains("<script>alert('xss')</script>"));
    }
}
