/*
 * Generated by ChatGPT.
 */
package com.myenterprise.rest.component;

import org.owasp.html.HtmlPolicyBuilder;
import org.owasp.html.PolicyFactory;
import org.springframework.stereotype.Component;

/**
 * A policy component for sanitizing HTML content generated by CKEditor.
 * <p>
 * This class defines a strict HTML sanitization policy using {@link HtmlPolicyBuilder}
 * to prevent cross-site scripting (XSS) attacks. It allows a specific set of HTML tags,
 * attributes, and styling while disallowing potentially dangerous elements
 * like scripts, iframes, and forms.
 * <p>
 * The policy is designed to clean up rich text content typically submitted from
 * a WYSIWYG editor like CKEditor, ensuring that only safe and expected
 * formatting is preserved.
 */
@Component
public class CKEditorSanitizerPolicy {

    /**
     * Private constructor to prevent instantiation of this utility class.
     */
    private CKEditorSanitizerPolicy(){}

    /**
     * A constant for the HTML 'table' tag, used to avoid magic strings.
     */
    private static final String TABLE = "table";

    /**
     * The immutable HTML sanitization policy factory.
     * <p>
     * This factory is used to create a sanitizer that processes HTML strings
     * according to the defined rules. It allows a specific set of tags for
     * structure, rich text, headers, lists, tables, links, and images,
     * while disallowing potentially harmful elements.
     */
    public static final PolicyFactory CKEDITOR_POLICY = new HtmlPolicyBuilder()

            // basic structure
            .allowElements("p", "br", "div", "span", "blockquote")

            // rich text
            .allowElements("b", "strong", "i", "em", "u", "s", "sub", "sup", "small", "big", "code", "pre")

            // headers
            .allowElements("h1", "h2", "h3", "h4", "h5", "h6")

            // lists
            .allowElements("ul", "ol", "li")

            // tables
            .allowElements(TABLE, "thead", "tbody", "tfoot", "tr", "td", "th")
            .allowAttributes("colspan", "rowspan").onElements("td", "th")

            // links
            .allowElements("a")
            .allowAttributes("href").onElements("a")
            .allowAttributes("target").onElements("a")
            .allowStandardUrlProtocols()

            // images
            .allowElements("img")
            .allowAttributes("src", "alt", "title", "width", "height").onElements("img")
            .allowUrlProtocols("http", "https") // 'data' protocol is not trusted

            // alignment and common styles
            .allowAttributes("style").onElements("span", "p", "div", TABLE, "td", "th", "img")
            .allowStyling() // Allow CSS properties trusted, you can do it more restricted

            // classes and styles (limited)
            .allowAttributes("class").onElements("span", "div", "p", TABLE, "img")

            // avoid scripts
            .disallowElements("script", "iframe", "object", "embed", "form", "input", "textarea")

            .toFactory();
}