openapi: 3.0.3
info:
  title: Hotel CRUD API
  version: 1.0.0
  description: API REST para gestionar hoteles.

servers:
  - url: https://localhost:8080/api/v1

paths:
  /hotels:
    $ref: paths/hotels.yaml
  /hotels/{id}:
    $ref: paths/hotelsId.yaml

security:
  - bearerAuth: []

components:
  schemas:
    Hotel:
      $ref: components/schemas.yaml#/Hotel
    Error:
      $ref: components/schemas.yaml#/Error
    HotelInput:
      $ref: components/schemas.yaml#/HotelInput
  responses:
    404Response:
      $ref: components/responses.yaml#/404Response
    500Response:
      $ref: components/responses.yaml#/500Response
    429Response:
      $ref: components/responses.yaml#/429Response
  headers:
    XRateLimitRemaining:
      $ref: components/headers.yaml#/XRateLimitRemaining
  securitySchemes:
    bearerAuth:
      $ref: components/securitySchemes.yaml#/bearerAuth
